services:
  aro-pra-fe:
    build:
      context: ../frontend
      dockerfile: ../deploy/frontend/Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - aro-pra-be
    networks:
      - aro-pra-network

  aro-pra-be:
    build:
      context: ../backend
      dockerfile: ../deploy/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:8080" # 닫기
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - aro-pra-data
    networks:
      - aro-pra-network

  aro-pra-data:
    image: mongo:7.0
    container_name: aro-pra-data
    restart: unless-stopped
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
    volumes:
      - aro-pra-data-storage:/data/aro-pra-db
    networks:
      - aro-pra-network

volumes:
  aro-pra-data-storage:
    driver: local

networks:
  aro-pra-network:
    driver: bridge
